# Generated by Django 3.2.19 on 2024-12-12 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Depart_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Depart_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('D_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hms.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('Medicine_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Medicine_name', models.CharField(max_length=200)),
                ('Cost', models.IntegerField()),
                ('Side_effect', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('P_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Staff_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(choices=[('ADMIN', 'Administrator'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('RECEPTIONIST', 'Receptionist'), ('TECHNICIAN', 'Technician'), ('Medical Staff', 'Medical Staff'), ('Support Staff', 'Support Staff')], max_length=150, null=True)),
                ('Depart_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hms.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Room_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Room_no', models.IntegerField()),
                ('Room_type', models.CharField(choices=[('General Ward', 'General Ward'), ('ICU', 'ICU'), ('Maternity Room', 'Maternity Room'), ('Isolation Room', 'Isolation Room'), ('Day Care Room', 'Day Care Room'), ('Delux Room', 'Delux Room')], max_length=200)),
                ('status', models.CharField(choices=[('available', 'available'), ('occupied', 'occupied')], max_length=100)),
                ('P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.medicine')),
                ('P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.patient')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='P_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.patient'),
        ),
        migrations.CreateModel(
            name='Lab_Test',
            fields=[
                ('Test_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Test_name', models.CharField(max_length=200)),
                ('Test_date', models.DateField()),
                ('Test_result', models.CharField(max_length=255)),
                ('D_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.doctor')),
                ('P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_P', models.IntegerField()),
                ('P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('Bill_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Total_amount', models.IntegerField()),
                ('Pay_date', models.DateField()),
                ('Pay_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit/Debit Card', 'Credit/Debit Card'), ('Mobile Wallet', 'Mobile Wallet'), ('Insurance', 'Insurance'), ('UPI', 'UPI')], max_length=100)),
                ('P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.doctor')),
                ('P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Appointment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Appointment_datetime', models.DateTimeField()),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled'), ('Completed', 'Completed'), ('No-Show', 'No-Show')], default='PENDING', max_length=255)),
                ('D_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.doctor')),
                ('P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.patient')),
            ],
        ),
    ]
