# Generated by Django 3.2.19 on 2024-12-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_auto_20241212_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='Cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Medicine_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Side_effect',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
